### ISSUE TITLE
How to decode XHR response?

### ISSUE THREAD

**Issue by barneycarroll** [paroga/cbor-js#2]
`CBOR.decode( responseString )` chides me for not passing in an `ArrayBuffer`. I naively tried `CBOR.decode( new ArrayBuffer( responseString ) )` but that gives me `Uncaught RangeError: Offset is outside the bounds of the DataView` in `readUint8`.

**Comment by paroga** [comment]
Can you attach a full script with specific values? Unfortunately I do not see what value your responseString variable has.
Which environment (browser) do you use exactly?

**Comment by paroga** [comment]
Since I did not get a response for over a week I'll close this issue.
A possible solution for your problem might be listed at http://stackoverflow.com/questions/6965107/converting-between-strings-and-arraybuffers.
