### ISSUE TITLE
Publish on npm

### ISSUE THREAD

**Issue by letmaik** [paroga/cbor-js#5]
It would be wonderful if this library would be published on [npm](https://www.npmjs.com/package/leaflet). This would make it way easier to include it as dependency when you already have a npm workflow.

**Comment by paroga** [comment]
Do you use npm for client dependencies? Isn't bower the correct way to do that? I'm not sure if it is a good idea to publish the package on different registries.
And for the server side I'd recommend using the existing cbor package.

**Comment by neothemachine** [comment]
Yeah all these registries are a mess anyway... I'm using JSPM now which can directly include your library from github, so just ignore my request regarding npm. My second request would have been to have cbor-js on a CDN for really easy use (for beginners mainly), but thanks to rawgit.com this is not necessary anymore. So, closing, all fine! :)

**Comment by neothemachine** [comment]
I'm reopening this as I have a use case now where I'd like to use cbor-js server-side on node.js. I see no reason to not publish it on npm. Many client-only libraries are published on npm as well, and cbor-js can run on a server as well, so it makes even more sense. I also don't see a problem with publishing on multiple registries (bower, npm), it is common practice.

**Comment by neothemachine** [comment]
I just discovered that github repositories can be referenced as dependency within npm, making this issue low priority since there is a way without publishing to npm.
